export const PAYEMENT_FETCH_REQUEST = ' PAYEMENT_FETCH_REQUEST';
export const PAYEMENT_FETCH_SUCCESS = 'PAYEMENT_FETCH_SUCCESS';
export const PAYEMENT_FETCH_FAIL = 'PAYEMENT_FETCH_FAIL';
export const PAYEMENT_FETCH_RESET = 'PAYEMENT_FETCH_RESET';


export const DATA_FETCH_REQUEST = ' DATA_FETCH_REQUEST';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_FAIL = 'DATA_FETCH_FAIL';
export const DATA_FETCH_RESET = 'DATA_FETCH_RESET';
