export const ORDER_FETCH_REQUEST = "ORDER_FETCH_REQUEST";
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_FAIL = "ORDER_FETCH_FAIL";
export const ORDER_FETCH_RESET = "ORDER_FETCH_RESET";
