export const PRODUCT_FETCH_REQUEST =" PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS =" PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL =" PRODUCT_FETCH_FAIL";

export const PRODUCT_ADD_REQUEST =" PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS =" PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAIL =" PRODUCT_ADD_FAIL";

