export const PRODUCT_FETCH_REQUEST = " PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS = " PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL = " PRODUCT_FETCH_FAIL";
export const PRODUCT_FETCH_RESET = " PRODUCT_FETCH_RESET";

export const PRODUCT_POST_REQUEST = "PRODUCT_POST_REQUEST";
export const PRODUCT_POST_SUCCESS = "PRODUCT_POST_SUCCESS";
export const PRODUCT_POST_FAIL = "PRODUCT_POST_FAIL";
export const PRODUCT_POST_RESET = "PRODUCT_POST_RESET";

export const COMPANY_FETCH_REQUEST = "COMPANY_FETCH_REQUEST";
export const COMPANY_FETCH_SUCCESS = "COMPANY_FETCH_SUCCESS";
export const COMPANY_FETCH_FAIL = "COMPANY_FETCH_FAIL";
export const COMPANY_FETCH_RESET = "COMPANY_FETCH_RESET";

export const CATEGORY_FETCH_REQUEST = "CATEGORY_FETCH_REQUEST";
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS";
export const CATEGORY_FETCH_FAIL = "CATEGORY_FETCH_FAIL";
export const CATEGORY_FETCH_RESET = "CATEGORY_FETCH_RESET";
